Switch checking logic

diff --git a/.github/workflows/pr-checks.yaml b/.github/workflows/pr-checks.yaml
--- a/.github/workflows/pr-checks.yaml
+++ b/.github/workflows/pr-checks.yaml
@@ -10,11 +10,11 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Check for do-not-merge label
+        if: contains(github.event.pull_request.labels.*.name, 'do-not-merge')
         run: |
-          for label in ${{ github.event.pull_request.labels }}; do
-            echo "Checking label: $label"
-            if [[ "$label" == *"do-not-merge"* ]]; then
-              echo "Error: PR contains do-not-merge label"
-              exit 1
-            fi
-          done
+            echo "Error: PR contains do-not-merge label"
+            exit 1
+      - name: Success
+        run: |
+            echo "Success: PR does not contain do-not-merge label"
+
